# Generated by Django 2.2.7 on 2019-11-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_porfile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfile',
            name='test',
        ),
    ]
